spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_management?serverTimezone=UTC
    username: root
    password: "0518"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
